version: 2
jobs:
  build:
    docker:
      - image: circleci/ubuntu-server
    steps:
      - checkout
      - run: sudo apt-get update; sudo apt-get install -y git make g++ liblog4cpp5-dev libvpx-dev libx264-dev libjpeg-dev 
      - run: make
